/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package messages.worker

import kotlin.test.Test
import kotlin.test.assertNotNull

class MessagesWorkerAppTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = MessagesWorkerApp()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
